# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-01 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tags',
        ),
        migrations.AddField(
            model_name='image',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
